import { Header } from "@/components/Header";
import { useEffect } from "react";

const Terms = () => {
  useEffect(() => {
    document.title = "Terms & Conditions — RedditLens";
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 container max-w-3xl py-16 px-4">
        <h1 className="text-3xl font-bold mb-2">Terms & Conditions</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: June 8, 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-muted-foreground [&_h2]:text-foreground [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-8 [&_h2]:mb-3 [&_h3]:text-foreground [&_h3]:text-base [&_h3]:font-medium [&_h3]:mt-4 [&_h3]:mb-2 [&_strong]:text-foreground [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1 [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:space-y-1">
          <p>
            These Terms & Conditions ("Terms") govern your use of <strong>RedditLens</strong> (the "Service"), operated by <strong>Sanzox</strong> (<a href="https://www.sanzox.com/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">sanzox.com</a>). By accessing or using the Service, you agree to be bound by these Terms.
          </p>

          <h2>1. Service Description</h2>
          <p>
            RedditLens is an AI-powered market research tool that analyzes publicly available Reddit discussions to generate insights, pain point analysis, competitor intelligence, and idea validation reports.
          </p>

          <h2>2. Account Registration</h2>
          <ul>
            <li>You must create an account (via Google or email) to use the search functionality.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You must provide accurate and complete information during registration.</li>
            <li>You must be at least 13 years old to use the Service.</li>
          </ul>

          <h2>3. Free & Paid Plans</h2>
          <h3>Free Plan</h3>
          <ul>
            <li>Limited to <strong>3 searches per month</strong>.</li>
            <li>Includes basic AI reports, pain point detection, and Build or Skip verdict.</li>
            <li>Usage limits are enforced per account, IP address, and device.</li>
          </ul>

          <h3>Paid Plans</h3>
          <ul>
            <li>Paid subscriptions unlock unlimited searches and premium features.</li>
            <li>Payments are processed through <strong>LemonSqueezy</strong>.</li>
            <li>Subscriptions renew automatically unless cancelled.</li>
            <li>You can cancel at any time from your LemonSqueezy account portal.</li>
          </ul>

          <h2>4. Acceptable Use</h2>
          <p>You agree <strong>not</strong> to:</p>
          <ul>
            <li>Create multiple accounts to circumvent usage limits.</li>
            <li>Use automated bots, scrapers, or scripts to access the Service.</li>
            <li>Attempt to reverse-engineer, decompile, or exploit the Service.</li>
            <li>Use the Service for any illegal or unauthorized purpose.</li>
            <li>Resell, redistribute, or commercially exploit generated reports without permission.</li>
            <li>Submit malicious input designed to manipulate AI responses (prompt injection).</li>
          </ul>

          <h2>5. Intellectual Property</h2>
          <ul>
            <li><strong>Our IP:</strong> The Service, including its design, code, algorithms, and branding, is owned by Sanzox.</li>
            <li><strong>Your Content:</strong> You retain ownership of any data you input. You grant us a limited license to process it for generating reports.</li>
            <li><strong>Generated Reports:</strong> Reports generated by the Service are licensed to you for personal or internal business use.</li>
            <li><strong>Reddit Data:</strong> Reddit content analyzed by the Service is publicly available and belongs to its respective authors.</li>
          </ul>

          <h2>6. AI-Generated Content Disclaimer</h2>
          <p>
            Reports generated by RedditLens are produced by artificial intelligence and should be treated as <strong>informational guidance only</strong>. We do not guarantee the accuracy, completeness, or reliability of AI-generated analysis. You should independently verify any business decisions based on our reports.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law:
          </p>
          <ul>
            <li>The Service is provided <strong>"as is"</strong> without warranties of any kind.</li>
            <li>We are not liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</li>
            <li>Our total liability shall not exceed the amount you paid for the Service in the preceding 12 months.</li>
            <li>We are not responsible for decisions made based on AI-generated reports.</li>
          </ul>

          <h2>8. Refunds</h2>
          <ul>
            <li>We offer refunds on a case-by-case basis within <strong>14 days</strong> of purchase.</li>
            <li>To request a refund, contact us at <a href="mailto:shakib@redditlens.app" className="text-primary hover:underline">shakib@redditlens.app</a>.</li>
          </ul>

          <h2>9. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account if you violate these Terms, abuse the Service, or engage in fraudulent activity. Upon termination, your right to use the Service ceases immediately.
          </p>

          <h2>10. Modifications</h2>
          <p>
            We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms. Material changes will be communicated via email or a notice on the website.
          </p>

          <h2>11. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with applicable laws. Any disputes shall be resolved through good-faith negotiation before pursuing legal action.
          </p>

          <h2>12. Contact</h2>
          <p>
            For questions about these Terms, contact us at:{" "}
            <a href="mailto:shakib@redditlens.app" className="text-primary hover:underline">
              shakib@redditlens.app
            </a>
          </p>
        </div>
      </main>
    </div>
  );
};

export default Terms;
